# Generated by Django 3.0.5 on 2020-04-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('upc', models.IntegerField(blank=True, unique=True, verbose_name='UPC')),
                ('product_id', models.IntegerField(blank=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=500)),
                ('model_number', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('active_update_date', models.DateTimeField()),
                ('regular_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('price_update_date', models.DateTimeField()),
                ('affiliate_url', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True, verbose_name='Image URL')),
                ('image_thumbnail', models.TextField(blank=True, verbose_name='Image Thumbnail URL')),
                ('energy_guide', models.TextField(blank=True, verbose_name='Energy Guide Label URL')),
                ('download_date', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.ProductCategory'),
        ),
    ]
