# Generated by Django 3.0.5 on 2020-04-21 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_mapped', models.BooleanField(default=False, editable=False, null=True, verbose_name='Mapped')),
                ('is_primary', models.BooleanField(default=False, help_text='If checked, other manufacturers will be able to map to this one. If not, this manufacturer will only be able to map to others. Note: you will not be able to change this box after this manufacturer has been mapped or mapped to until you remove the conflicted maps. If you have tried mapping a primary, you will have to navigate your browser away.', verbose_name='Primary')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('eia', 'EIA Download'), ('ccms', 'CCMS Download'), ('bb', 'Bestbuy Download'), ('maps', 'Mappings')], max_length=200, unique=True)),
                ('source_type', models.CharField(choices=[('Product', 'Product Source'), ('Reference', 'Reference Source')], max_length=100)),
                ('category_model_class', models.CharField(max_length=200)),
                ('category_name_field', models.CharField(max_length=200)),
                ('manufacturer_model_class', models.CharField(max_length=200)),
                ('manufacturer_name_field', models.CharField(max_length=200)),
                ('model_model_class', models.CharField(max_length=200)),
                ('model_number_field', models.CharField(max_length=200)),
                ('model_manufacturer_field', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '- Sources',
            },
        ),
        migrations.CreateModel(
            name='TestCategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_id', models.PositiveIntegerField()),
                ('product_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, verbose_name='Model Number Pattern')),
                ('primary_manufacturer', models.ForeignKey(limit_choices_to={'is_primary': True}, on_delete=django.db.models.deletion.CASCADE, to='maps.Manufacturer', verbose_name='Manufacturer')),
                ('source', models.ForeignKey(limit_choices_to={'source_type': 'Reference'}, on_delete=django.db.models.deletion.CASCADE, to='maps.Source', verbose_name='Reference Source')),
            ],
            options={
                'unique_together': {('pattern', 'primary_manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='Model Number')),
                ('is_mapped', models.BooleanField(default=False, editable=False, verbose_name='Map Status')),
                ('primary_manufacturer', models.ForeignKey(limit_choices_to={'is_primary': True}, on_delete=django.db.models.deletion.CASCADE, to='maps.Manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'unique_together': {('number', 'primary_manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='ModelMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('map_choice', models.BooleanField(default=False)),
                ('product_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maps.ProductModel')),
                ('reference_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.ReferenceModel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Category')),
                ('mapped_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped', to='maps.Category')),
            ],
            options={
                'verbose_name': 'Category Map',
                'verbose_name_plural': 'Category Mappings',
                'unique_together': {('category', 'mapped_category')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='mappings',
            field=models.ManyToManyField(blank=True, related_name='_category_mappings_+', through='maps.CategoryMap', to='maps.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Source'),
        ),
        migrations.CreateModel(
            name='ManufacturerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('map_choice', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'is_primary': False}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maps.Manufacturer')),
                ('matched_manufacturer', models.ForeignKey(limit_choices_to={'is_primary': True}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maps.Manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer Map',
                'verbose_name_plural': 'Manufacturer Mappings',
                'unique_together': {('manufacturer', 'matched_manufacturer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'source')},
        ),
    ]
