# Generated by Django 3.0.5 on 2020-04-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategorymap',
            name='reference_category_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcategorymap',
            name='reference_category_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
