# Generated by Django 3.0.5 on 2020-04-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200420_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcategorymap',
            old_name='product_category_type',
            new_name='product_category_class',
        ),
        migrations.RenameField(
            model_name='testcategorymap',
            old_name='reference_category_type',
            new_name='reference_category_class',
        ),
    ]
