# Generated by Django 3.0.5 on 2020-04-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EfficiencyMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Efficiency Metric',
                'verbose_name_plural': 'Efficiency Metrics',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('efficiency_metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estar.EfficiencyMetric')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estar_uid', models.IntegerField(unique=True, verbose_name='ENERGY STAR Unique Identifier')),
                ('model_number', models.CharField(max_length=200)),
                ('efficiency_value', models.FloatField()),
                ('life', models.FloatField(blank=True, null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estar.BrandName')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estar.ProductCategory')),
            ],
        ),
    ]
