# Generated by Django 3.0.5 on 2020-04-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('month_year', models.DateField(verbose_name='Month-Year')),
                ('value', models.FloatField()),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Electricity Rate',
                'verbose_name_plural': 'Electricity Rates',
            },
        ),
    ]
